export const DUMMY_PRODUCTS = [
  {
    id: 1,
    image: 'product-img/laptop.jpg',
    name: 'Laptop',
    description: 'High performance laptop for work and gaming',
    price: 80000,
    stock: 5,
  },
  {
    id: 2,
    image: 'product-img/iphone.jpg',
    name: 'Iphone 17 Pro MAX',
    description: 'Latest smartphone with amazing features',
    price: 170000,
    stock: 0,
  },
  {
    id: 3,
    image: 'product-img/airbuds.jpg',
    name: 'Apple Airbuds',
    description: 'Noise cancelling over-ear headphones',
    price: 24000,
    stock: 0,
  },
  {
    id: 4,
    image: 'product-img/watch.jpg',
    name: 'Smart Watch',
    description: 'Track your fitness and notifications',
    price: 7000,
    stock: 1,
  },
  {
    id: 5,
    image: 'product-img/camera.jpg',
    name: 'Sony DSLR Camera',
    description: 'Capture moments with high clarity',
    price: 245000,
    stock: 4,
  },
  {
    id: 6,
    image: 'product-img/shoes.jpg',
    name: 'Running Shoes',
    description: 'Comfortable shoes for daily running',
    price: 10000,
    stock: 2,
  },
  {
    id: 7,
    image: 'product-img/tshirt.jpg',
    name: 'T-Shirt',
    description: 'Cotton t-shirt for casual wear',
    price: 800,
    stock: 10,
  },
  {
    id: 8,
    image: 'product-img/backpack.jpg',
    name: 'Backpack',
    description: 'Durable backpack for travel and work',
    price: 2500,
    stock: 3,
  },
  {
    id: 9,
    image: 'product-img/ipad-mini.jpg',
    name: 'Apple Ipad Mini',
    description: 'Lightweight tablet for entertainment',
    price: 55000,
    stock: 0,
  },
  {
    id: 10,
    image: 'product-img/keyboard.jpg',
    name: 'Keyboard',
    description: 'Mechanical keyboard with RGB lights',
    price: 4000,
    stock: 6,
  },
  {
    id: 11,
    image: 'product-img/mouse.jpg',
    name: 'Mouse',
    description: 'Wireless mouse with smooth tracking',
    price: 1200,
    stock: 2,
  },
  {
    id: 12,
    image: 'product-img/monitor.jpg',
    name: 'Monitor',
    description: '24-inch full HD display',
    price: 12000,
    stock: 5,
  },
  {
    id: 13,
    image: 'product-img/speaker.jpg',
    name: 'Bluetooth Speaker',
    description: 'Portable speaker with deep bass',
    price: 5500,
    stock: 1,
  },
  {
    id: 14,
    image: 'product-img/powerbank.jpg',
    name: 'Power Bank',
    description: '10000mAh fast charging power bank',
    price: 1500,
    stock: 0,
  },
  {
    id: 15,
    image: 'product-img/desk.jpg',
    name: 'Office Desk',
    description: 'Spacious wooden office desk',
    price: 15000,
    stock: 3,
  },
  {
    id: 16,
    image: 'product-img/chair.jpg',
    name: 'Office Chair',
    description: 'Ergonomic chair for comfort',
    price: 9000,
    stock: 2,
  },
  {
    id: 17,
    image: 'product-img/earbuds.jpg',
    name: 'Earbuds',
    description: 'True wireless earbuds with charging case',
    price: 3500,
    stock: 7,
  },
  {
    id: 18,
    image: 'product-img/gaming-console.jpg',
    name: 'Gaming PS5',
    description: 'Next-gen gaming console experience',
    price: 150000,
    stock: 1,
  },
  {
    id: 19,
    image: 'product-img/mic.jpg',
    name: 'Microphone',
    description: 'Studio quality microphone for recording',
    price: 6000,
    stock: 4,
  },
  {
    id: 20,
    image: 'product-img/printer.jpg',
    name: 'Printer',
    description: 'All-in-one wireless printer',
    price: 8000,
    stock: 0,
  },
  {
    id: 21,
    image: 'product-img/router.jpg',
    name: 'WiFi Router',
    description: 'High speed dual band router',
    price: 2500,
    stock: 5,
  },

  {
    id: 22,
    image: 'product-img/fridge.jpg',
    name: 'Refrigerator',
    description: 'Energy efficient double door refrigerator',
    price: 65000,
    stock: 4,
  },
  {
    id: 23,
    image: 'product-img/ac.jpg',
    name: 'Air Conditioner',
    description: '1.5 Ton split AC with fast cooling',
    price: 45000,
    stock: 1,
  },
  {
    id: 24,
    image: 'product-img/washing-machine.jpg',
    name: 'Washing Machine',
    description: 'Fully automatic washing machine',
    price: 28000,
    stock: 0,
  },
  {
    id: 25,
    image: 'product-img/oven.jpg',
    name: 'Microwave Oven',
    description: 'Convection microwave for fast cooking',
    price: 10000,
    stock: 3,
  },
  {
    id: 26,
    image: 'product-img/fan.jpg',
    name: 'Ceiling Fan',
    description: 'High speed fan with low power consumption',
    price: 3000,
    stock: 6,
  },
  {
    id: 27,
    image: 'product-img/iron.jpg',
    name: 'Electric Iron',
    description: 'Steam iron for wrinkle-free clothes',
    price: 1200,
    stock: 2,
  },
  {
    id: 28,
    image: 'product-img/toaster.jpg',
    name: 'Toaster',
    description: '2-slice pop-up bread toaster',
    price: 15000,
    stock: 5,
  },
  {
    id: 29,
    image: 'product-img/blender.jpg',
    name: 'Blender',
    description: 'Multi-purpose kitchen blender',
    price: 3000,
    stock: 1,
  },
  {
    id: 30,
    image: 'product-img/gas-stove.jpg',
    name: 'Gas Stove',
    description: '2 burner gas stove with glass top',
    price: 3500,
    stock: 0,
  },
  {
    id: 31,
    image: 'product-img/water-purifier.jpg',
    name: 'Water Purifier',
    description: 'RO + UV water purifier system',
    price: 12000,
    stock: 3,
  },
];
